FROM node:16-buster-slim

# set working directory
WORKDIR /frontend

# add `/app/node_modules/.bin` to $PATH
ENV PATH /frontend/node_modules/.bin:$PATH

# install app dependencies
COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install --frozen-lockfile

# add app
COPY ./frontend ./

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]