version: '3'

services:
  elasticsearch:
      build: 
        context: .
        dockerfile: Dockerfile.elasticsearch
      volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - "cluster.name=elasticsearch"
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        - "XPACK_SECURITY_ENABLED=false"
      networks:
        - my-network
      healthcheck:
        test: "curl http://elasticsearch:9200"
        interval: "10s"
        timeout: "3s"
        retries: 60
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
        test: "curl http://backend:5000/"
        interval: "10s"
        timeout: "3s"
        retries: 60
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      backend:
        condition: service_healthy
      
networks:
  my-network:
    driver: bridge
